apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api-blue
  labels:
    app: demo-api
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-api
      version: blue
  template:
    metadata:
      labels:
        app: demo-api
        version: blue
    spec:
      containers:
        - name: api
          image: __IMAGE__   # sustituido dinámicamente por el pipeline con el tag exacto (nunca :latest)
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
