apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api-green
  labels:
    app: demo-api
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-api
      version: green
  template:
    metadata:
      labels:
        app: demo-api
        version: green
    spec:
      containers:
        - name: api
          image: bnjmn265/demo-api:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
